name = "BioMarkovChains"
uuid = "f861b655-cb5f-42ce-b66a-341b542d4f2c"
authors = ["Camilo García-Botero<ca.garcia2@uniandes.edu.co>"]
version = "0.9.0"

[deps]
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
VectorizedKmers = "2ef45bd6-4c2b-43d8-88b3-40597287359a"

[weakdeps]
DiscreteMarkovChains = "8abcb7ef-b365-4f7b-ac38-56893fb62f9f"
MarkovChainHammer = "38c40fd0-bccb-4723-b30d-b2caea0ad8d9"

[extensions]
DiscreteMarkovChainsExt = "DiscreteMarkovChains"
MarkovChainHammerExt = "MarkovChainHammer"

[compat]
BioSequences = "3"
DiscreteMarkovChains = "0.2"
MarkovChainHammer = "0"
PrecompileTools = "1"
VectorizedKmers = "0.8"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
