name = "BioMarkovChains"
uuid = "f861b655-cb5f-42ce-b66a-341b542d4f2c"
authors = ["Camilo García<ca.garcia2@uniandes.edu.co>"]
version = "0.1.0"

[deps]
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
MarkovChainHammer = "38c40fd0-bccb-4723-b30d-b2caea0ad8d9"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[compat]
BioSequences = "3"
MarkovChainHammer = "0.0.9"
PrecompileTools = "1"
TestItemRunner = "0.2"
TestItems = "0.1"
julia = "1.9"
